"""Interface layer for GUI-backend communication."""

from .protocol import GUIAPI, BackendAPI, MessageChannel
from .types import (
    AgentId,
    AgentResponse,
    AgentResultMessage,
    AgentStatus,
    AgentType,
    BlockedNoticeMessage,
    Checkpoint,
    ConfigChange,
    Error,
    Message,
    MessageType,
    PeerQueryMessage,
    PeerReplyMessage,
    ProgressNoteMessage,
    ResearchNotePublishedMessage,
    RestartRequest,
    StatusChange,
    ToolCallMessage,
    ToolResult,
    UserMessage,
    normalize_agent_id,
)

__all__ = [
    "MessageType",
    "AgentType",
    "AgentId",
    "normalize_agent_id",
    "AgentStatus",
    "Message",
    "UserMessage",
    "AgentResponse",
    "AgentResultMessage",
    "ToolCallMessage",
    "ToolResult",
    "StatusChange",
    "ConfigChange",
    "RestartRequest",
    "Checkpoint",
    "BlockedNoticeMessage",
    "Error",
    "PeerQueryMessage",
    "PeerReplyMessage",
    "ProgressNoteMessage",
    "ResearchNotePublishedMessage",
    "MessageChannel",
    "BackendAPI",
    "GUIAPI",
]
